spring:
  config:
    activate:
      on-profile: dev-token

security:
  jwt:
    token:
      secretKey: ${JWT_SECRET_KEY}
      access:
        validTime: 1800000
      refresh:
        validTime: 3600000
